# action.yml
name: 'Run Golang App'
description: 'Run Golang app with github action'
inputs:
  argument-number-one:  # id of input
    description: 'Argument one'
    required: true
    default: 'One'
  argument-number-two:  # id of input
    description: 'Argument two'
    required: true
    default: 'two'
  argument-number-three:  # id of input
    description: 'Argument three'
    required: false
    default: 'three'
outputs:
  time: # id of output
    description: 'Time result output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.argument-number-one }}
    - ${{ inputs.argument-number-two }}
    - ${{ inputs.argument-number-three }}