# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  argument-number-one:  # id of input
    description: 'Argument one'
    required: true
    default: 'One'
  argument-number-two:  # id of input
    description: 'Argument two'
    required: true
    default: 'two'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.argument-number-one }}
    - ${{ inputs.argument-number-two }}