on: [push]

jobs:
  # test_github_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.18

  #     - name: Build
  #       run: go build -v ./...

  #     - name: List out dir
  #       run: ls -l

  #     - name: Upload math result for job 1
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: gha-test-golang
  #         path: gha-test-golang

  test_github_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: List out dir
        run: ls -l

      # - name: Download gha-test-golang
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: gha-test-golang

      - name: Github Action Step
        uses: ./ 
        id: gha
        with:
          argument-number-one: 'Sammi Tests'
          argument-number-two: '666'
          argument-number-three: 'myns'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"